//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexRisk.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyticDailyRecord : IAnalyticDailyRecord
    {
        public System.DateTime Date { get; set; }
        public double CpiDifference { get; set; }
        public double CpiTendency { get; set; }
        public double InterestRateDifference { get; set; }
        public double InterestRateTendency { get; set; }
        public double TradeBalanceByUk { get; set; }
        public double TradeBalanceByUs { get; set; }
        public double DebtGrowthUk { get; set; }
        public double DebtGrowthUs { get; set; }
        public double ForexTendency { get; set; }
        public int Outcome { get; set; }
        public int Id { get; set; }
    }

    public interface IAnalyticDailyRecord
    {
        DateTime Date { get; set; }
        double CpiDifference { get; set; }
        double CpiTendency { get; set; }
        double InterestRateDifference { get; set; }
        double InterestRateTendency { get; set; }
        double TradeBalanceByUk { get; set; }
        double TradeBalanceByUs { get; set; }
        double DebtGrowthUk { get; set; }
        double DebtGrowthUs { get; set; }
        double ForexTendency { get; set; }
        int Outcome { get; set; }
    }
}
