//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexRisk.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForexDataEntities : DbContext
    {
        public ForexDataEntities()
            : base("name=ForexDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalyticRecord> AnalyticRecords { get; set; }
        public virtual DbSet<AnalyticQuarterlyRecord> AnalyticQuarterlyRecords { get; set; }
    }
}
